L1 documentation
Huddly/sdk pull request #508
Opened 2021-12-15 13:40 UTC by brikendr

- Camera info
- Camera upgrade
- Camera Detections
- Camera PTZ & Enabling/Disabling Autozoom

2021-12-15 14:51 UTC, eskilgh requested changes

2021-12-15 14:51 UTC, eskilgh commented on examples/huddly_l1/upgrade.js
> +const performUpgrade = (attachedDevice, cpioFilePath) => {
nice

2021-12-15 14:51 UTC, eskilgh commented on examples/huddly_l1/detections.js
> +    detector = manager.getDetector({ objectFilter: ['person'], DOWS: true, rawDetections: true });
remove rawDetections param

2021-12-15 14:51 UTC, eskilgh commented on examples/huddly_l1/detections.js
> +    detector.on('DETECTIONS', (data = []) => {
I think the data = [] as default is misleading, as it should never really happen given proper implementation on the sdk.

2021-12-16 11:10 UTC, eskilgh approved these changes
👍👍👍👍👍👍

2021-12-16 11:11 UTC, pkhansen approved these changes

2021-12-16 11:21 UTC, merged